config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    if @flat.update(flat_params)
      redirect_to @flat, notice: "Flat was succcesfully updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_url, notice: "Flat was successfully destroyed"

  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= form_with model: flat do |f| %>
              <p><%= f.label :Name, class:"form-label" %>
              <%= f.text_field :name, class:"form-control"%></p>
              <p><%= f.label :Address, class:"form-label" %>
              <%= f.text_field :address, class:"form-control"%></p>
              <p><%= f.label :Description, class:"form-label" %>
              <%= f.text_area :description, size: "60x5", class:"form-control" %></p>
              <p><%= f.label :Price_per_night, class:"form-label" %>
              <%= f.text_field :price_per_night, class:"form-control"%></p>
              <p><%= f.label :Number_Of_Guests, class:"form-label" %>
              <%= f.text_field :number_of_guests, class:"form-control"%></p>

              <%= f.submit class:"btn btn-secondary" %>
            <% end %>

app/views/flats/edit.html.erb
<section class="vh-100">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-8 col-xl-6">
        <div class="card rounded-3">
          <p class="card-header"><span class="h2 me-2">Edit Flat</span></p>
          <div class="card-body p-4 m-1">
            <%= render "form", flat: @flat %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/flats/index.html.erb
<div class="container">
  <h1 class="mt-3">All our Flats</h1>
  <div class="row">
    <% @num = 0 %>
    <% @flats.each do |flat| %>
      <% @num += 1 %>
      <div class="card mt-3 me-3 mb-3 p-0" style="width: 25rem;">
        <div class="col">
          <%= image_tag "flat#{@num}.png", class:"card-img-top"%>
          <div class="card-body h-auto">
            <h5 class="card-title"><%= flat.name  %></h5>
            <p class="card-text"><%= flat.description %></p>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item"><%= flat.address %></li>
            <li class="list-group-item"><i class="fa-solid fa-people-roof fa-lg"></i> <%= flat.number_of_guests %> <i class="fa-solid fa-euro-sign fa-lg"></i><%= flat.price_per_night %></li>
            <li style="list-style-type:none"></li>
          </ul>
          <div class="card-body">
            <%= link_to 'More Info', flat_path(flat), class:"card-link" %>
            <%= link_to 'Edit', edit_flat_path(flat), class:"card-link" %>
            <%= link_to 'Remove', flat_path(flat), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class:"card-link" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/flats/new.html.erb
<section class="vh-100">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-8 col-xl-6">
        <div class="card rounded-3">
          <p class="card-header"><span class="h2 me-2">Add Flat</span></p>
          <div class="card-body p-4 m-1">
            <%= render "form", flat: @flat %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/flats/show.html.erb
<h1>Show</h1>

app/views/flats/test.html.erb
<section class="vh-100">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-8 col-xl-6">
        <div class="card rounded-3">
          <p class="card-header"><span class="h2 me-2">Add Flat</span></p>
          <div class="card-body p-4 m-1">
            <%= form_with model: @flat do |f| %>
              <p><%= f.label :Name, class:"form-label" %>
                <%= f.text_field :name, class:"form-control"%></p>
              <p><%= f.label :Address, class:"form-label" %>
                <%= f.text_field :address, class:"form-control"%></p>
              <p><%= f.label :Description, class:"form-label" %>
                <%= f.text_area :description, size: "60x5", class:"form-control" %></p>
              <p><%= f.label :Price_per_night, class:"form-label" %>
                <%= f.text_field :price_per_night, class:"form-control"%></p>
              <p><%= f.label :Number_Of_Guests, class:"form-label" %>
                <%= f.text_field :number_of_guests, class:"form-control"%></p>
              <%= f.submit class:"btn btn-secondary" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <nav class="navbar navbar-light bg-light">
      <div class="container-fluid">
        <%= link_to 'Simlpe Airbnb', flats_path, class:"navbar-brand ms-2" %>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
          <%= link_to 'Add Flat', new_flat_path, class:"btn btn-outline-success text-nowrap ms-2" %>
        </form>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>